### POST auth token
POST http://localhost:8000/auth/token/
Content-Type: application/json

{
  "username": "l",
  "password": "qwer"
}

> {% client.global.set("auth_token", response.body.token); %}

### GET health check
GET http://localhost:8000/health_check/

### POST stars
POST http://localhost:8000/api/stars/
Authorization: Token {{auth_token}}
Content-Type: application/json

{
  "name": "Sol",
  "level": 1
}

### GET stars
GET http://localhost:8000/api/stars/

### POST stars
POST http://localhost:8000/api/planets/
Authorization: Token {{auth_token}}
Content-Type: application/json

{
  "name": "Mars",
  "star": 1,
  "extreme_environment": false,
  "resources": [1]
}

### GET planets
GET http://localhost:8000/api/planets/

### POST moons
POST http://localhost:8000/api/moons/
Authorization: Token {{auth_token}}
Content-Type: application/json

{
  "name": "Sol",
  "level": 1
}

### GET moons
GET http://localhost:8000/api/moons/

### POST resources
POST http://localhost:8000/api/resources/
Authorization: Token {{auth_token}}
Content-Type: application/json

{
  "name": "Iron",
  "abbreviation": "Fe",
  "rarity": 0
}

### GET resources
GET http://localhost:8000/api/resources/
