### POST auth token
POST http://localhost:8000/auth/token/
Content-Type: application/json

{
  "username": "l",
  "password": "qwer"
}

> {% client.global.set("auth_token", response.body.token); %}

### GET health check
GET http://localhost:8000/health_check/

### POST stars
POST http://localhost:8000/api/stars/
Authorization: Token {{auth_token}}
Content-Type: application/json

{
  "name": "Sol",
  "level": 1
}

### GET stars
GET http://localhost:8000/api/stars/

### GET planets
GET http://localhost:8000/api/planets/

### GET moons
GET http://localhost:8000/api/moons/

### GET resources
GET http://localhost:8000/api/resources/
